### ISSUE TITLE
Client.api_url returns wrong value

### ISSUE THREAD

**Issue by karibou** [scaleway/scaleway-sdk-python#174]
When using Client.from_config_file_and_env(profile_name='my_very_own_profile')
where the profile has `api_url` different from the default in the config.yaml file, it still picks up the default URL even if this one is not defined in the config.yaml file and not the `api_url` as stated in the profile.

Here is an example : 
using following profile : 
```
profiles: 
  my_very_own_profile:
    access_key: ...
    api_url: htp://this.is.a.very.bad.url
```
Doing : 
```
from scaleway import Client
from scaleway.instance.v1.api import InstanceV1API
client = Client.from_config_file_and_env(profile_name='my_very_own_profile')
client.api_url
'https://api.scaleway.com'
